# ---------------------------------------------------------------------#
# Russian characters added by Vinely#3309 (https://github.com/Vinellon )
# ---------------------------------------------------------------------#
'%img_coin%': 10
'뀁': 8
'Ё': 6
'Й': 5
'Ц': 5
'У': 5
'К': 5
'Е': 5
'Н': 5
'Г': 5
'Ш': 7
'Щ': 8
'З': 5
'Х': 5
'Ъ': 5
'Ф': 7
'Ы': 7
'В': 5
'А': 5
'П': 5
'Р': 5
'О': 6
'Л': 5
'Д': 6
'Ж': 7
'Э': 5
'Я': 5
'Ч': 6
'С': 5
'М': 6
'И': 5
'Т': 6
'Ь': 5
'Б': 5
'Ю': 7
'ё': 5
'й': 5
'ц': 5
'у': 5
'к': 5
'е': 5
'н': 5
'г': 5
'ш': 5
'щ': 6
'з': 4
'х': 5
'ъ': 5
'ф': 5
'ы': 6
'в': 5
'а': 5
'п': 6
'р': 6
'о': 5
'л': 5
'д': 5
'ж': 7
'э': 4
'я': 5
'ч': 5
'с': 5
'м': 5
'и': 5
'т': 5
'ь': 5
'б': 5
'ю': 6